---
title: "Partie 1"
author: "DIAKITE Moussa"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(gtsummary)
library(sf)
library(gt)
library(ggplot2)
# chargement des packages nécessaires
```
##### corps du code
```{r}
setwd("E:/Projet R")
# et pour changer de répertoire

#-----------------------------------------------
#        IMPORTATION ET MISE EN FORME
#-----------------------------------------------


projet<-read_excel('Base_Partie 1.xlsx')
head(projet)
# data.frame nommé projet
# head : pour lecture du data.frame


selection_variable <- projet[, c("key", "q1", "q2", "q23", "q24",
                                 "q24a_1", "q24a_2", "q24a_3", 
                                 "q24a_4", "q24a_5", "q24a_6", 
                                 "q24a_7", "q24a_9", "q24a_10",
                                 "q25", "q26", "q12", "q14b",
                                 "q16", "q17", "q19", "q20", 
                                 "filiere_1", "filiere_2", 
                                 "filiere_3", "filiere_4", 
                                 "q8", "q81", "gps_menlatitude", 
                                 "gps_menlongitude", 
                                 "submissiondate", "start", "today")]
# création de sous ensemble de data.frame

nombre_valeur_manquante <- colSums(is.na(selection_variable))
# pour avoir le nombre de valeur manquante par variable

tableau_valeur_manquante <- data.frame(variable=names(nombre_valeur_manquante),
                                       nombre_valeur_manquante=nombre_valeur_manquante)

# création de data.frame pour résumer les valeurs manquantes

print(tableau_valeur_manquante)
# on affiche le tableau des valeurs manquantes 

valeur_manquante_key<- is.na(projet$key)
# verification pour l'existence d'une varible manquante pour key

pme_concerne<-projet[valeur_manquante_key,]
# pour avoir les pme concernés

print(pme_concerne)
# affichage des pme concernés


#----------------------------------------------
#            CREATION DE VARIABLES
#----------------------------------------------

projet <- projet %>% rename(region=q1)
# renom de q1 en region

projet <- projet %>% rename(departement=q2)
# renom de q2 en departement

projet <- projet %>% rename(sexe=q23)
#renom de q23 en sexe 

projet$sexe_2 <- ifelse(projet$sexe=="femme",1,0)
# creation de la variable sexé_2 et application du choix binaire

langues <- projet %>% select(key, starts_with("q24a_"))
# creation du data.frame nommé langue

head(langues)
#afficher les premières lignes de langues 

projet$parle<- projet %>% select(key, starts_with("q24a_"))
# creation d'une variable langue et une autre alternative est :
# proje$parle <- rowSums(projet[, starts_with("q24a_")])

langues<- projet %>% select (key, parle)
# creation de langue à partir de key et parle

fusion_projet <- merge(projet, langues, by="key")
# on fussionne les data.frame projet et langues en 
# utilisant key comme la clé de fusion

head(fusion_projet)
# lecture des premières lignes


#------------------------------------------------
#           ANALYSE DESCRIPTIVE
#------------------------------------------------

repartition_sexe <- table(projet$sexe)
# compte le nombre de chaque type de sexe

repartition_niveau_instruction <- table(projet$q25)
# compte l'occurence de chaque niveau d'instruction

repartition_statut_juridique <- table(projet$q12)
# l'occurence de chaque statut juridique

repartition_proprietaire_locataire <- table(projet$q81)
# denombre l'occurence de chaque statut proprietaire_locataire

repartition_statut_sexe <- table(projet$q12, projet$sexe)
# tableau croisé en statut juridique et sexe

repartition_niveau_instruction_sexe <- table(projet$q25, projet$sexe)
# tableau croisé niveu d'instruction et sexe

repartition_proprietaire_sexe <- table(projet$q81, projet$sexe)
# tableau croisé entre statut proprietaire_locataire et sexe

tableau_synthese_1 <- projet %>% select(sexe, q25, q12, q81) %>% tbl_summary() %>% as_gt()
tableau_synthese_1
# tableau synthèse pour les premières répartitions


variables_pour_resume <- c("q26", "q16", "q17", "q19", "q20")

# Rassembler les variables de filière en une seule colonne
fusion_projet_long <- fusion_projet %>%
  pivot_longer(cols = starts_with("filiere_"), names_to = "filiere", values_to = "filiere_value")

# Créer un tableau de résumé pour les variables sélectionnées, groupées par "filiere"
tableau_resume <- fusion_projet_long %>%
  select(filiere, all_of(variables_pour_resume)) %>%
  tbl_summary(by = filiere, missing = "no") %>%
  add_stat_label() %>%
  modify_caption("Statistiques descriptives pour les variables sélectionnées par filière") %>%
  as_gt()

# Afficher le tableau de résumé
tableau_resume


#-----------------------------------------------------------
#                UN PEU DE CARTOGRAPHIE
#-----------------------------------------------------------

library(sf)
library(ggplot2)

projet_map <- st_as_sf(projet, coords = c("gps_menlongitude", "gps_menlatitude"), crs = 4326)
# on crée un objet sf à partir du data.frame projet

head(projet_map)

ggplot(data = projet_map) +
  geom_point(aes(x = "gps_menlongitude", y = "gps_menlatitude", color = sexe), size = 3) +
  labs(title = "Répartition spatiale des PME selon le sexe",
       x = "Longitude", y = "Latitude",
       color = "Sexe") +
  theme_minimal()
#représentation spatiale des PME selon le sexe


ggplot(data = projet_map) +
  geom_point(aes(x = "gps_menlongitude", y = "gps_menlatitude", color = q25), size = 3) +
  labs(title = "Répartition spatiale des PME selon le niveau d'instruction",
       x = "Longitude", y = "Latitude",
       color = "Niveau d'instruction") +
  theme_minimal()
# représentation spatiale des PME selon le niveau d'inscription


```

